# Generated by Django 2.1.3 on 2018-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='none@none.com', max_length=254),
            preserve_default=False,
        ),
    ]
