# Generated by Django 2.1.3 on 2018-11-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_article_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
