# Generated by Django 2.1.3 on 2018-11-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181115_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cites',
            field=models.ManyToManyField(related_name='cited', to='web.Article'),
        ),
    ]
