# Generated by Django 2.1.3 on 2018-11-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_article_cites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
