# Generated by Django 2.1.3 on 2018-11-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20181116_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('articles', models.ManyToManyField(related_name='keywords', to='web.Article')),
            ],
        ),
    ]
