# Generated by Django 2.1.3 on 2018-11-16 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeywordRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Article')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Keyword')),
            ],
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='articles',
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='articles',
            field=models.ManyToManyField(related_name='keywords', through='web.KeywordRank', to='web.Article'),
        ),
    ]
