# Generated by Django 2.1.3 on 2018-11-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20181116_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='first_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_articles', to='web.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_articles', to='web.Author'),
        ),
    ]
